/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import React, { useRef } from 'react';
import { useLoader } from '../../node_modules/react-three-fiber';
import { GLTFLoader } from '../../node_modules/three/examples/jsm/loaders/GLTFLoader';
import { draco } from '../../node_modules/drei';

export default function Ship(props) {
  const group = useRef();
  const { nodes, materials } = useLoader(
    GLTFLoader,
    '/assets/models/DS69F.gltf',
    draco('/draco-gltf/')
  );

  // // Register box as a physics body with mass
  // const ref = useCannon({ mass: 100000 }, body => {
  //   body.addShape(new CANNON.Box(new CANNON.Vec3(1, 1, 1)));
  //   body.position.set(...position);
  // });

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.31, 0.72, 0.22]}>
        <primitive object={nodes.Point_Orientation} />
      </group>
      <group position={[-0.31, 0.53, 0.22]}>
        <primitive object={nodes.Point001_Orientation} />
      </group>
      <group position={[-0.31, 0.94, 0.22]}>
        <primitive object={nodes.Point002_Orientation} />
      </group>
      <group position={[0.29, 0.53, 0.22]}>
        <primitive object={nodes.Point003_Orientation} />
      </group>
      <group position={[0.29, 0.94, 0.22]}>
        <primitive object={nodes.Point004_Orientation} />
      </group>
      <group position={[-0.31, 0.53, -0.35]}>
        <primitive object={nodes.Point005_Orientation} />
      </group>
      <group position={[-0.31, 0.94, -0.35]}>
        <primitive object={nodes.Point006_Orientation} />
      </group>
      <group position={[0.29, 0.53, -0.35]}>
        <primitive object={nodes.Point007_Orientation} />
      </group>
      <group position={[0.29, 0.94, -0.35]}>
        <primitive object={nodes.Point008_Orientation} />
      </group>
      <group position={[-0.01, 0.85, -0.04]} rotation={[1.65, 0, Math.PI]}>
        <primitive object={nodes.BridgeCam1_Orientation} />
      </group>
      <group position={[-0.01, 0.85, -0.69]} rotation={[1.65, 0, Math.PI]}>
        <primitive object={nodes.BridgeCam2_Orientation} />
      </group>
      <group position={[-0.31, 0.48, -1.49]} rotation={[Math.PI / 2, 0, 0]} scale={[0.09, 0.09, 0.09]}>
        <mesh material={nodes['Cylinder.003_0'].material} geometry={nodes['Cylinder.003_0'].geometry} />
        <mesh material={nodes['Cylinder.003_1'].material} geometry={nodes['Cylinder.003_1'].geometry} />
      </group>
      <mesh material={nodes.grill_bars.material} geometry={nodes.grill_bars.geometry} position={[-0.52, 0.49, -1.62]} />
      <mesh
        material={nodes.passenger_2_arm_rest.material}
        geometry={nodes.passenger_2_arm_rest.geometry}
        position={[-0.01, 0.76, -0.55]}
      />
      <mesh
        material={nodes.passenger_1_arm_rest.material}
        geometry={nodes.passenger_1_arm_rest.geometry}
        position={[-0.01, 0.76, 0.1]}
      />
      <mesh
        material={nodes.passenger_1_foot_rest.material}
        geometry={nodes.passenger_1_foot_rest.geometry}
        position={[0, 0.61, 0.14]}
      />
      <mesh
        material={nodes.passenger_1_seat.material}
        geometry={nodes.passenger_1_seat.geometry}
        position={[0, 0.66, 0.02]}
        rotation={[0, 0, 0]}
      />
      <mesh
        material={nodes.grill_support.material}
        geometry={nodes.grill_support.geometry}
        position={[0.12, 0.48, -1.58]}
        scale={[0.02, 0.15, 0.02]}
      />
      <mesh
        material={nodes.grill_limiter.material}
        geometry={nodes.grill_limiter.geometry}
        position={[-0.01, 0.45, -1.52]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.7, 0.17, 0.15]}
      />
      <mesh
        material={nodes.grill_bars_small.material}
        geometry={nodes.grill_bars_small.geometry}
        position={[-0.66, 0.47, -1.62]}
        scale={[0.01, 0.11, 0.01]}
      />
      <mesh
        material={nodes.grill_bars_medium.material}
        geometry={nodes.grill_bars_medium.geometry}
        position={[-0.57, 0.45, -1.62]}
      />
      <mesh
        material={nodes.grill_inside.material}
        geometry={nodes.grill_inside.geometry}
        position={[-0.01, 0.47, -1.57]}
        scale={[0.37, 0.42, 0.92]}
      />
      <mesh
        material={nodes.passenger_2_seat.material}
        geometry={nodes.passenger_2_seat.geometry}
        position={[0, 0.66, -0.63]}
        rotation={[0, 0, 0]}
      />
      <mesh
        material={nodes.passenger_2_foot_rest.material}
        geometry={nodes.passenger_2_foot_rest.geometry}
        position={[0, 0.61, -0.51]}
      />
      <mesh material={nodes.roof.material} geometry={nodes.roof.geometry} position={[0, 0.82, -0.91]} />
      <mesh
        material={materials.ShipHull}
        geometry={nodes.maintenance_cover.geometry}
        position={[-1, 0.27, 0.18]}
        rotation={[0, 0, 0.45]}
        scale={[0.12, 0.12, 0.12]}
      />
      <group position={[0, 0.5, 0]}>
        <mesh material={materials.ShipHull} geometry={nodes.Cube_0.geometry} />
        <mesh material={materials.Exhaust} geometry={nodes.Cube_1.geometry} />
      </group>
    </group>
  )
}
