// --------------------------------------------------------------- //
// Auto-generated by generatePluginCompletion().                   //
// Please commit this file.                                        //
// --------------------------------------------------------------- //

type PluginNames =
  'metadata' | 
  'core' | 
  'nodeOps' | 
  'player' | 
  'spacetimeControl' | 
  'navigation' | 
  'levelScene' | 
  'spaceScene' | 
  'localSpace' | 
  'offscreenGalaxyWorker' | 
  'html3dRenderer' | 
  'hud3D' | 
  'mouseDriver' | 
  'inputManager' | 
  'gamepadConnector' | 
  'reactBase' | 
  'gameMenu' | 
  'navMenu' | 
  'generalControl' | 
  'freeCam' | 
  'buckledPassenger' | 
  'helmControl' | 
  'electricalHousingModule' | 
  'propulsionManagerModule' | 
  'warpDriveModule' | 
  'generatorModule' | 
  'visorHudModule' | 
  'cockpitLightsModule' | 
  'externalLightsModule' | 
  'multimeterModule' | 
  'shipModuleHub' | 
  'devGimbal' | 
  'postBootChecks';

export {
  PluginNames,
}
