// --------------------------------------------------------------- //
// Auto-generated by generatePluginCompletion().                   //
// Please commit this file.                                        //
// --------------------------------------------------------------- //

type PluginNames =
  'metadata' | 
  'core' | 
  'nodeOps' | 
  'player' | 
  'spacetimeControl' | 
  'navigation' | 
  'levelScene' | 
  'spaceScene' | 
  'offscreenGalaxyWorker' | 
  'hud3D' | 
  'mouseDriver' | 
  'gamepadConnector' | 
  'inputManager' | 
  'generalControl' | 
  'freeCam' | 
  'shipPilot' | 
  'reactBase' | 
  'electricalHousingModule' | 
  'propulsionManagerModule' | 
  'warpDriveModule' | 
  'generatorModule' | 
  'visorHudModule' | 
  'cockpitLightsModule' | 
  'externalLightsModule' | 
  'multimeterModule' | 
  'shipModuleHub' | 
  'devGimbalPlugin';

export {
  PluginNames,
}
